### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by shang1219178163** [ChinaArJun/Tencent-NOW#11]
![2018-08-21 17 14 19](https://user-images.githubusercontent.com/3699729/44392838-b7478e00-a565-11e8-8373-959117b1211c.png)

**Comment by ChinaArJun** [comment]
-百度云盘链接:https://pan.baidu.com/s/1smNcwsX 密码:xpsq

-记得打开项目后将打包好的[ijkplayer ]拖入项目，不然会报错
