### ISSUE TITLE
项目跑不了 缺少IJKMediaFramework库

### ISSUE THREAD

**Issue by errorUserInfo** [ChinaArJun/Tencent-NOW#3]

**Comment by ChinaArJun** [comment]
目主要是基于ijkplayer 的. 最好是打包成framework
. 我也准备好了一份打包好的分享给大家
-百度云盘链接: https://pan.baidu.com/s/1jIEZN8M 密码: igcq
直接拖进工程里面

**Comment by iKater** [comment]
你好,支持ipv6 only 吗？
